### ISSUE TITLE
feat: longer traceback via "quit and dump" feature

### ISSUE THREAD

**Issue by alexander-held** [henryiii/uproot-browser#29]
While trying out the new `browse` functionality, I ran into an unexpected error when plotting a specific branch in a file where other similar branches seem to produce histograms without problems. The traceback that is shown by default in the window where the histogram would appear is quite short, and perhaps it would be useful for such cases to have a feature that allows to quit out and dump a more complete traceback to help with the debugging of such cases.

**Comment by henryiii** [comment]
I'm thinking "quit and dump" would also show how to get the object via uproot, and it would (possibly) also dump the plot if it has not errored.

**Comment by alexander-held** [comment]
For future reference, I managed to isolate the error I originally ran into when creating this issue, which I reported at https://github.com/scikit-hep/hist/issues/393.
